export const UPDATE_WISHLISTS = 'UPDATE_WISHLISTS';
export const CREATE_WISHLIST = 'CREATE_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';

export const SHOW_CREATE_WISHLIST_FORM = 'SHOW_CREATE_WISHLIST_FORM';
export const SHOW_REGISTER_FORM = 'SHOW_REGISTER_FORM';

export const ACCOUNT_REGISTRATION = 'ACCOUNT_REGISTRATION';
