export const CREATE_WISHLIST = 'CREATE_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';

export const UPDATE_STORE_WISHLISTS = 'UPDATE_STORE_WISHLISTS';

export const SHOW_WISHLIST_FORM = 'SHOW_WISHLIST_FORM';
export const SHOW_REGISTER_FORM = 'SHOW_REGISTER_FORM';
export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

export const TRIGGER_UPDATE_ACTION = 'TRIGGER_UPDATE_ACTION';

export const TOGGLE_WISHLIST_MODAL = 'TOGGLE_WISHLIST_MODAL';
export const TRIGGER_WISHLIST_MODAL = 'TRIGGER_WISHLIST_MODAL';
